// src/components/HistoryManager.tsx
import React, { useState, useMemo } from "react";
import {
  Modal,
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  ScrollView,
  ActivityIndicator,
  TextInput,
} from "react-native";
import {
  getSession,
  removeFromContext,
  updateSummary,
  type ChatMessage,
} from "../store/sessions";
import { getSettings } from "../store/settings";
import { buildConversationContext, type Message } from "../prompt/template";
import { buildPlannerMessages } from "../agent/planner";
import { buildWriterMessages } from "../agent/writer";
import { buildStatusManagerMessages } from "../agent/statusManager";
import { getLoreEntryTitles } from "../agent/loreRouter";
import { summarizeHistory, DEFAULT_SUMMARIZE_PROMPT } from "../prompt/summarizer";

interface Props {
  visible: boolean;
  sessionId: string;
  onClose: () => void;
}

export default function HistoryManager({ visible, sessionId, onClose }: Props) {
  const [mode, setMode] = useState<"view" | "summarize">("view");
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [summaryResult, setSummaryResult] = useState("");
  const [loading, setLoading] = useState(false);
  const [detail, setDetail] = useState<{ title: string; text: string } | null>(null);
  const [summarizedMsgIds, setSummarizedMsgIds] = useState<string[]>([]);
  const [summarizePrompt, setSummarizePrompt] = useState("");

  const session = getSession(sessionId);
  if (!session) return null;

  const settings = getSettings();

  // 构建三 Agent 的完整 context
  const { plannerSys, writerSys, statusSys, chatMessages } = useMemo(() => {
    const chatHistory = session.messages
      .filter((m) => m.messageType !== "status")
      .map((m) => ({ role: m.role, content: m.content, id: m.id } as any));

    if (settings.agentMode) {
      const card = session.characterCard;
      const userName = session.userName || "User";

      // Planner
      const plannerCtx = buildPlannerMessages(
        card, chatHistory, userName,
        session.summary || "", session.status || "", settings
      );
      const pSys = plannerCtx.filter((m: any) => m.role === "system");

      // Writer — 用真实对话历史做关键词匹配
      const writerRecentText = chatHistory.map((m: any) => m.content).join("\n");
      const writerLastUser = chatHistory.filter((m: any) => m.role === "user").pop()?.content;
      const writerCtx = buildWriterMessages(card, userName, "(Writing Guide — see actual message for content)", settings, writerRecentText, writerLastUser);
      const wSys = writerCtx.filter((m: any) => m.role === "system");

      // Status Manager
      const statusCtx = buildStatusManagerMessages(
        card, session.status || "", "(Latest text — see actual message for content)", settings
      );
      const sSys = statusCtx.filter((m: any) => m.role === "system");

      // Chat messages from planner (includes history)
      const chatMsgs = plannerCtx.filter(
        (m: any) => m.role === "user" || m.role === "assistant"
      );

      return {
        plannerSys: pSys,
        writerSys: wSys,
        statusSys: sSys,
        chatMessages: chatMsgs,
      };
    }

    // 普通模式
    const ctx = buildConversationContext(
      session.characterCard,
      chatHistory,
      session.userName || "User",
      session.summary || undefined,
      session.lastSummarizedIndex,
      settings,
      session.deletedMessageIds
    );
    return {
      plannerSys: [] as Message[],
      writerSys: [] as Message[],
      statusSys: ctx.filter((m: any) => m.role === "system"),
      chatMessages: ctx.filter((m: any) => m.role === "user" || m.role === "assistant"),
    };
  }, [session, settings]);

  // 提取实际注入的 entry 标题（直接调用 loreRouter，和运行时逻辑完全一致）
  const injectedEntries = useMemo(() => {
    if (!settings.agentMode) return null;
    const card = session.characterCard;
    const recentText = session.messages
      .filter((m) => m.messageType !== "status")
      .map((m) => m.content).join("\n");
    const statusRecentText = session.messages
      .findLast((m) => m.role === "assistant" && m.messageType !== "status")?.content?.slice(-2000) || "";

    return {
      planner: getLoreEntryTitles(card, "planner", recentText),
      writer: getLoreEntryTitles(card, "writer", recentText),
      status: getLoreEntryTitles(card, "status", statusRecentText),
    };
  }, [session, settings]);

  const [showPlanner, setShowPlanner] = useState(true);
  const [showWriter, setShowWriter] = useState(true);
  const [showStatus, setShowStatus] = useState(true);
  const [showNormal, setShowNormal] = useState(true);

  const toggleSelect = (idx: number) => {
    const key = String(idx);
    const next = new Set(selected);
    if (next.has(key)) next.delete(key);
    else next.add(key);
    setSelected(next);
  };

  const selectAll = () => {
    if (selected.size === chatMessages.length) {
      setSelected(new Set());
    } else {
      setSelected(new Set(chatMessages.map((_, i) => String(i))));
    }
  };

  const handleDelete = (idx: number) => {
    const msg = chatMessages[idx] as any;
    if (msg?.id) {
      removeFromContext(sessionId, msg.id);
    }
  };

  const handleSummarize = async () => {
    const indices =
      mode === "summarize" && selected.size > 0
        ? [...selected].map(Number).sort((a, b) => a - b)
        : chatMessages.map((_, i) => i);

    const msgs = indices.map((i) => ({
      role: (chatMessages[i] as any).role as "user" | "assistant",
      content: (chatMessages[i] as any).content as string,
    }));

    const selectedIds = indices.map((i) => (chatMessages[i] as any).id as string);

    if (msgs.length === 0) return;

    setLoading(true);
    try {
      const effectivePrompt = summarizePrompt.trim() || undefined;
      const result = await summarizeHistory(settings, "", msgs, effectivePrompt);
      setSummaryResult(result || "(empty)");
      setSummarizedMsgIds(selectedIds);
    } catch (e: any) {
      setSummaryResult(`Error: ${e.message}`);
    } finally {
      setLoading(false);
    }
  };

  const applySummary = () => {
    if (summaryResult && !summaryResult.startsWith("Error:")) {
      const lastIdx = summarizedMsgIds.length > 0
        ? Math.max(
            ...summarizedMsgIds.map((id) =>
              session.messages.findIndex((m) => m.id === id)
            ).filter((i) => i >= 0),
            -1
          )
        : session.messages.length - 1;

      updateSummary(
        sessionId,
        summaryResult,
        lastIdx >= 0 ? lastIdx : session.messages.length - 1
      );
      setSummaryResult("");
      setSummarizedMsgIds([]);
      setMode("view");
      setSelected(new Set());
    }
  };

  const renderAgentSection = (
    label: string,
    color: string,
    sysMsgs: Message[],
    entryTitles: string[],
    show: boolean,
    setShow: (v: boolean) => void
  ) => (
    <View key={label}>
      <TouchableOpacity
        style={styles.systemToggle}
        onPress={() => setShow(!show)}
      >
        <Text style={[styles.systemToggleText, { color }]}>
          {show ? "▼" : "▶"} {label} ({sysMsgs.length})
          {entryTitles.length > 0 ? ` · ${entryTitles.length} entries` : ""}
        </Text>
      </TouchableOpacity>
      {show && (
        <>
          {entryTitles.length > 0 && (
            <View style={styles.entryList}>
              {entryTitles.map((t, i) => (
                <Text key={i} style={styles.entryItem}>
                  + {t}
                </Text>
              ))}
            </View>
          )}
          {sysMsgs.map((msg: any, idx: number) => (
            <TouchableOpacity
              key={idx}
              style={styles.systemBlock}
              onPress={() =>
                setDetail({ title: `${label} · System ${idx + 1}`, text: msg.content })
              }
            >
              <Text style={[styles.agentRole, { color }]}>system {idx + 1}</Text>
              <Text style={styles.systemContent} numberOfLines={8}>
                {msg.content}
              </Text>
            </TouchableOpacity>
          ))}
        </>
      )}
    </View>
  );

  return (
    <Modal visible={visible} animationType="slide" presentationStyle="pageSheet">
      <View style={styles.container}>
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity onPress={onClose}>
            <Text style={styles.backBtn}>← Back</Text>
          </TouchableOpacity>
          <Text style={styles.title}>Context ({chatMessages.length} msgs)</Text>
          <View style={{ width: 50 }} />
        </View>

        <ScrollView style={styles.body}>
          {/* Mode buttons */}
          <View style={styles.modeRow}>
            <TouchableOpacity
              style={[styles.modeBtn, mode === "view" && styles.modeActive]}
              onPress={() => { setMode("view"); setSelected(new Set()); }}
            >
              <Text style={[styles.modeText, mode === "view" && styles.modeTextActive]}>
                View
              </Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={[styles.modeBtn, mode === "summarize" && styles.modeActive]}
              onPress={() => setMode("summarize")}
            >
              <Text style={[styles.modeText, mode === "summarize" && styles.modeTextActive]}>
                Summarize
              </Text>
            </TouchableOpacity>
          </View>

          {/* System prompts */}
          {plannerSys.length > 0 ? (
            <>
              <Text style={styles.sectionHint}>Agent V2 — three-agent context</Text>
              {renderAgentSection(
                "Planner Agent",
                "#3b82f6",
                plannerSys,
                injectedEntries?.planner || [],
                showPlanner,
                setShowPlanner
              )}
              {renderAgentSection(
                "Writer Agent",
                "#10b981",
                writerSys,
                injectedEntries?.writer || [],
                showWriter,
                setShowWriter
              )}
              {renderAgentSection(
                "Status Manager",
                "#f59e0b",
                statusSys,
                injectedEntries?.status || [],
                showStatus,
                setShowStatus
              )}
            </>
          ) : (
            <TouchableOpacity
              style={styles.systemToggle}
              onPress={() => setShowNormal(!showNormal)}
            >
              <Text style={styles.systemToggleText}>
                {showNormal ? "▼" : "▶"} System Prompt ({statusSys.length})
              </Text>
              {showNormal &&
                statusSys.map((msg: any, idx: number) => (
                  <TouchableOpacity
                    key={idx}
                    style={styles.systemBlock}
                    onPress={() =>
                      setDetail({ title: `System ${idx + 1}`, text: msg.content })
                    }
                  >
                    <Text style={styles.systemRole}>system {idx + 1}</Text>
                    <Text style={styles.systemContent} numberOfLines={10}>
                      {msg.content}
                    </Text>
                  </TouchableOpacity>
                ))}
            </TouchableOpacity>
          )}

          {/* Chat messages */}
          {chatMessages.map((msg: any, idx: number) => {
            const isUser = msg.role === "user";
            const selKey = String(idx);
            const isSelected = selected.has(selKey);
            const isDeleted = session.deletedMessageIds.includes(msg.id);

            return (
              <View
                key={idx}
                style={[
                  styles.msgRow,
                  isDeleted && styles.msgDeleted,
                  isSelected && styles.msgSelected,
                ]}
              >
                {(mode === "summarize") && (
                  <TouchableOpacity
                    style={styles.checkArea}
                    onPress={() => toggleSelect(idx)}
                  >
                    <View
                      style={[
                        styles.checkbox,
                        isSelected && styles.checkboxChecked,
                      ]}
                    >
                      {isSelected && (
                        <Text style={styles.checkmark}>✓</Text>
                      )}
                    </View>
                  </TouchableOpacity>
                )}
                <TouchableOpacity
                  style={styles.msgContent}
                  onPress={() =>
                    setDetail({ title: isUser ? "You" : "AI", text: msg.content })
                  }
                >
                  <View style={styles.msgHeader}>
                    <Text style={[styles.msgRole, isUser && styles.msgRoleUser]}>
                      {isUser ? "You" : "AI"}
                    </Text>
                    {isDeleted ? (
                      <Text style={styles.deletedBadge}>removed</Text>
                    ) : null}
                  </View>
                  <Text style={styles.msgPreview} numberOfLines={3}>
                    {msg.content}
                  </Text>
                </TouchableOpacity>
                {!isDeleted && (
                  <TouchableOpacity
                    style={styles.deleteBtn}
                    onPress={() => handleDelete(idx)}
                  >
                    <Text style={styles.deleteBtnText}>✕</Text>
                  </TouchableOpacity>
                )}
              </View>
            );
          })}

          {/* Summarize controls */}
          {mode === "summarize" && (
            <View style={styles.summarySection}>
              <Text style={styles.sectionLabel}>Prompt</Text>
              <TextInput
                style={styles.promptInput}
                value={summarizePrompt}
                onChangeText={setSummarizePrompt}
                placeholder={DEFAULT_SUMMARIZE_PROMPT}
                placeholderTextColor="#555"
                multiline
                numberOfLines={3}
              />

              <TouchableOpacity onPress={selectAll}>
                <Text style={styles.selectAllText}>
                  {selected.size === chatMessages.length
                    ? "Deselect All"
                    : `Select All (${selected.size}/${chatMessages.length})`}
                </Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={styles.summarizeBtn}
                onPress={handleSummarize}
                disabled={loading}
              >
                {loading ? (
                  <ActivityIndicator color="#fff" />
                ) : (
                  <Text style={styles.summarizeText}>
                    Summarize {selected.size > 0 ? `Selected (${selected.size})` : "All"}
                  </Text>
                )}
              </TouchableOpacity>

              {summaryResult ? (
                <View style={styles.resultBox}>
                  <Text style={styles.resultLabel}>Result:</Text>
                  <Text style={styles.resultText}>{summaryResult}</Text>
                  {!summaryResult.startsWith("Error:") &&
                    summaryResult !== "(empty)" && (
                      <View style={styles.resultBtns}>
                        <TouchableOpacity
                          style={styles.applyBtn}
                          onPress={applySummary}
                        >
                          <Text style={styles.applyBtnText}>Apply</Text>
                        </TouchableOpacity>
                        <TouchableOpacity
                          style={styles.discardBtn}
                          onPress={() => setSummaryResult("")}
                        >
                          <Text style={styles.discardBtnText}>Discard</Text>
                        </TouchableOpacity>
                      </View>
                    )}
                </View>
              ) : null}
            </View>
          )}
        </ScrollView>

        {/* Detail overlay */}
        {detail && (
          <View style={styles.detailOverlay}>
            <View style={styles.detailBox}>
              <View style={styles.detailHeader}>
                <Text style={styles.detailTitle}>{detail.title}</Text>
                <TouchableOpacity onPress={() => setDetail(null)}>
                  <Text style={styles.detailClose}>✕</Text>
                </TouchableOpacity>
              </View>
              <ScrollView style={styles.detailBody}>
                <Text style={styles.detailText}>{detail.text}</Text>
              </ScrollView>
            </View>
          </View>
        )}
      </View>
    </Modal>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#1a1a2e" },
  header: {
    flexDirection: "row", justifyContent: "space-between", alignItems: "center",
    paddingHorizontal: 14, paddingTop: 54, paddingBottom: 12,
    backgroundColor: "#16213e", borderBottomWidth: 1, borderBottomColor: "#2a2a4a",
  },
  backBtn: { color: "#a0a0b8", fontSize: 16 },
  title: { color: "#e0e0e0", fontSize: 16, fontWeight: "600" },
  body: { flex: 1, padding: 14 },

  // Mode
  modeRow: { flexDirection: "row", gap: 10, marginBottom: 14 },
  modeBtn: {
    flex: 1, backgroundColor: "#16213e", borderRadius: 8,
    padding: 10, alignItems: "center", borderWidth: 1, borderColor: "#2a2a4a",
  },
  modeActive: { borderColor: "#e94560", backgroundColor: "rgba(233,69,96,0.1)" },
  modeText: { color: "#888", fontSize: 14 },
  modeTextActive: { color: "#e94560", fontWeight: "600" },

  // System
  sectionHint: { color: "#10b981", fontSize: 11, marginBottom: 8 },
  systemToggle: { marginBottom: 10 },
  systemToggleText: { color: "#a0a0b8", fontSize: 13 },
  systemBlock: {
    backgroundColor: "#16213e", borderRadius: 8, padding: 10, marginBottom: 8,
    borderWidth: 1, borderColor: "#2a2a4a",
  },
  systemRole: { color: "#e94560", fontSize: 11, marginBottom: 4 },
  agentRole: { fontSize: 11, marginBottom: 4, fontWeight: "600" },
  systemContent: { color: "#888", fontSize: 12, lineHeight: 17 },
  entryList: {
    backgroundColor: "rgba(0,0,0,0.2)", borderRadius: 6,
    padding: 8, marginBottom: 8, marginLeft: 12,
  },
  entryItem: { color: "#f0c040", fontSize: 11, lineHeight: 16 },

  // Messages
  msgRow: {
    flexDirection: "row", alignItems: "flex-start",
    paddingVertical: 8, paddingHorizontal: 10,
    borderBottomWidth: 1, borderBottomColor: "#1a1a2e",
    borderRadius: 6, marginBottom: 2,
  },
  msgDeleted: { opacity: 0.4, backgroundColor: "rgba(233,69,96,0.05)" },
  msgSelected: { backgroundColor: "rgba(233,69,96,0.08)" },
  checkArea: { paddingRight: 10, paddingTop: 2 },
  checkbox: {
    width: 20, height: 20, borderRadius: 4,
    borderWidth: 1, borderColor: "#555",
    justifyContent: "center", alignItems: "center",
  },
  checkboxChecked: { backgroundColor: "#e94560", borderColor: "#e94560" },
  checkmark: { color: "#fff", fontSize: 12, fontWeight: "700" },
  msgContent: { flex: 1 },
  msgHeader: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 2 },
  msgRole: { color: "#3b82f6", fontSize: 11, fontWeight: "600" },
  msgRoleUser: { color: "#e94560" },
  deletedBadge: { color: "#e94560", fontSize: 10, backgroundColor: "rgba(233,69,96,0.15)", paddingHorizontal: 6, paddingVertical: 1, borderRadius: 4 },
  msgPreview: { color: "#c0c0c0", fontSize: 13, lineHeight: 18 },
  deleteBtn: { paddingLeft: 8, paddingTop: 2 },
  deleteBtnText: { color: "#e94560", fontSize: 16, fontWeight: "700" },

  // Summary
  summarySection: { marginTop: 16 },
  sectionLabel: { color: "#a0a0b8", fontSize: 13, marginBottom: 6 },
  promptInput: {
    backgroundColor: "#1a1a2e", color: "#e0e0e0", borderRadius: 8,
    padding: 12, fontSize: 13, borderWidth: 1, borderColor: "#2a2a4a",
    minHeight: 70, textAlignVertical: "top", marginBottom: 12,
  },
  selectAllText: { color: "#3b82f6", fontSize: 13, marginBottom: 10 },
  summarizeBtn: {
    backgroundColor: "#e94560", borderRadius: 10,
    padding: 14, alignItems: "center",
  },
  summarizeText: { color: "#fff", fontSize: 15, fontWeight: "600" },
  resultBox: {
    marginTop: 14, backgroundColor: "#16213e", borderRadius: 12,
    padding: 16, borderWidth: 1, borderColor: "#2a2a4a",
  },
  resultLabel: { color: "#888", fontSize: 12, marginBottom: 8 },
  resultText: { color: "#e0e0e0", fontSize: 14, lineHeight: 20 },
  applyBtn: {
    flex: 1, backgroundColor: "#3b82f6", borderRadius: 8,
    padding: 12, alignItems: "center",
  },
  applyBtnText: { color: "#fff", fontSize: 14, fontWeight: "600" },
  resultBtns: { flexDirection: "row", gap: 10, marginTop: 12 },
  discardBtn: {
    flex: 1, borderRadius: 8, padding: 12, alignItems: "center",
    borderWidth: 1, borderColor: "#555",
  },
  discardBtnText: { color: "#a0a0b8", fontSize: 14 },

  // Detail
  detailOverlay: {
    position: "absolute", top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: "rgba(0,0,0,0.7)", justifyContent: "center", alignItems: "center",
  },
  detailBox: {
    backgroundColor: "#16213e", borderRadius: 16, width: "92%", maxHeight: "80%",
    borderWidth: 1, borderColor: "#2a2a4a",
  },
  detailHeader: {
    flexDirection: "row", justifyContent: "space-between", alignItems: "center",
    padding: 16, borderBottomWidth: 1, borderBottomColor: "#2a2a4a",
  },
  detailTitle: { color: "#e0e0e0", fontSize: 16, fontWeight: "600" },
  detailClose: { color: "#e94560", fontSize: 20, fontWeight: "700" },
  detailBody: { padding: 16 },
  detailText: { color: "#e0e0e0", fontSize: 14, lineHeight: 22 },
});

// fake/strange/frontend/src/components/HistoryManager.vue
<template>
  <div v-if="visible" class="sheet">
    <!-- Header -->
    <header class="header">
      <button class="back-btn" @click="emit('close')">← Back</button>
      <span class="title">Context ({{ chatMessages.length }} msgs)</span>
      <span class="spacer"></span>
    </header>

    <div class="body">
      <!-- Mode buttons -->
      <div class="mode-row">
        <button
          class="mode-btn"
          :class="{ active: mode === 'view' }"
          @click="switchMode('view')"
        >
          View
        </button>
        <button
          class="mode-btn"
          :class="{ active: mode === 'summarize' }"
          @click="mode = 'summarize'"
        >
          Summarize
        </button>
      </div>

      <div v-if="!context" class="loading-text">Loading context…</div>

      <template v-else>
        <!-- System prompts -->
        <div class="system-group">
          <button class="system-toggle" @click="showNormal = !showNormal">
            <span class="system-toggle-text">
              {{ showNormal ? "▼" : "▶" }} System Prompt ({{ systemMessages.length }})
            </span>
          </button>
          <template v-if="showNormal">
            <button
              v-for="(msg, idx) in systemMessages"
              :key="'n' + idx"
              class="system-block"
              @click="setDetail(`System ${idx + 1}`, msg.content)"
            >
              <div class="system-role">system {{ idx + 1 }}</div>
              <div class="system-content clamp-10">{{ msg.content }}</div>
            </button>
          </template>
        </div>

        <!-- Chat messages -->
        <div
          v-for="(msg, idx) in chatMessages"
          :key="'m' + idx"
          class="msg-row"
          :class="{ selected: isSelected(idx) }"
        >
          <div v-if="mode === 'summarize'" class="check-area" @click="toggleSelect(idx)">
            <div class="checkbox" :class="{ checked: isSelected(idx) }">
              <span v-if="isSelected(idx)" class="checkmark">✓</span>
            </div>
          </div>
          <div class="msg-content" @click="setDetail(msg.role === 'user' ? 'You' : 'AI', msg.content)">
            <div class="msg-role" :class="{ user: msg.role === 'user' }">
              {{ msg.role === "user" ? "You" : "AI" }}
            </div>
            <div class="msg-preview clamp-3">{{ msg.content }}</div>
          </div>
          <button v-if="msg.id" class="delete-btn" @click="handleDelete(idx)">✕</button>
        </div>

        <!-- Summarize controls -->
        <div v-if="mode === 'summarize'" class="summary-section">
          <label class="section-label">Prompt</label>
          <textarea
            v-model="summarizePrompt"
            class="prompt-input"
            placeholder="Summarize the conversation so far, preserving key plot points, character details, and recent events."
          ></textarea>

          <button class="select-all" @click="selectAll">
            {{
              selected.size === chatMessages.length
                ? "Deselect All"
                : `Select All (${selected.size}/${chatMessages.length})`
            }}
          </button>

          <button class="summarize-btn" :disabled="loading" @click="handleSummarize">
            <span v-if="loading" class="spinner"></span>
            <span v-else>
              Summarize {{ selected.size > 0 ? `Selected (${selected.size})` : "All" }}
            </span>
          </button>

          <div v-if="summaryResult" class="result-box">
            <div class="result-label">Result:</div>
            <div class="result-text">{{ summaryResult }}</div>
            <div
              v-if="
                !summaryResult.startsWith('Error:') &&
                summaryResult !== '(empty)'
              "
              class="result-btns"
            >
              <button class="apply-btn" @click="applySummary">Apply</button>
              <button class="discard-btn" @click="summaryResult = ''">Discard</button>
            </div>
          </div>
        </div>
      </template>
    </div>

    <!-- Detail overlay -->
    <div v-if="detail" class="detail-overlay">
      <div class="detail-box">
        <div class="detail-header">
          <span class="detail-title">{{ detail.title }}</span>
          <button class="detail-close" @click="detail = null">✕</button>
        </div>
        <div class="detail-body">
          <div class="detail-text">{{ detail.text }}</div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from "vue";
import * as api from "../api";
import { useSessionsStore } from "../stores/sessions";
import type { ContextView } from "../types";

const props = defineProps<{ visible: boolean; sessionId: string }>();
const emit = defineEmits<{ (e: "close"): void }>();

const sessionsStore = useSessionsStore();

const context = ref<ContextView | null>(null);
const mode = ref<"view" | "summarize">("view");
const selected = ref<Set<string>>(new Set());
const summaryResult = ref("");
const loading = ref(false);
const detail = ref<{ title: string; text: string } | null>(null);
const summarizedMsgIds = ref<string[]>([]);
const summarizePrompt = ref("");

const showNormal = ref(true);

const chatMessages = computed(() => context.value?.chatMessages ?? []);
const systemMessages = computed(() => context.value?.systemMessages ?? []);

async function loadContext(): Promise<void> {
  try {
    context.value = await api.getContext(props.sessionId);
  } catch (e) {
    console.warn("[history] getContext failed:", e);
    context.value = null;
  }
}

watch(
  () => props.visible,
  async (v) => {
    if (v) {
      mode.value = "view";
      selected.value = new Set();
      summaryResult.value = "";
      summarizedMsgIds.value = [];
      summarizePrompt.value = "";
      detail.value = null;
      await loadContext();
    }
  }
);

function switchMode(m: "view" | "summarize"): void {
  mode.value = m;
  selected.value = new Set();
}

function isSelected(idx: number): boolean {
  return selected.value.has(String(idx));
}

function toggleSelect(idx: number): void {
  const key = String(idx);
  const next = new Set(selected.value);
  if (next.has(key)) next.delete(key);
  else next.add(key);
  selected.value = next;
}

function selectAll(): void {
  if (selected.value.size === chatMessages.value.length) {
    selected.value = new Set();
  } else {
    selected.value = new Set(chatMessages.value.map((_, i) => String(i)));
  }
}

function setDetail(title: string, text: string): void {
  detail.value = { title, text };
}

async function handleDelete(idx: number): Promise<void> {
  const msg = chatMessages.value[idx];
  if (msg?.id) {
    await sessionsStore.removeFromContext(props.sessionId, msg.id);
    await loadContext();
  }
}

async function handleSummarize(): Promise<void> {
  const msgs = chatMessages.value;
  if (msgs.length === 0) return;

  const indices =
    mode.value === "summarize" && selected.value.size > 0
      ? [...selected.value].map(Number).sort((a, b) => a - b)
      : msgs.map((_, i) => i);

  const ids = indices
    .map((i) => msgs[i]?.id)
    .filter((id): id is string => !!id);

  if (indices.length === 0) return;

  loading.value = true;
  try {
    const result = await api.summarize(props.sessionId, {
      messageIds: ids,
      prompt: summarizePrompt.value.trim(),
    });
    summaryResult.value = result.summary || "(empty)";
    summarizedMsgIds.value = ids;
  } catch (e) {
    summaryResult.value = `Error: ${(e as Error)?.message ?? e}`;
  } finally {
    loading.value = false;
  }
}

async function applySummary(): Promise<void> {
  if (
    !summaryResult.value ||
    summaryResult.value.startsWith("Error:") ||
    summaryResult.value === "(empty)"
  ) {
    return;
  }
  try {
    await api.applySummary(props.sessionId, {
      summary: summaryResult.value,
      messageIds: summarizedMsgIds.value,
    });
    await sessionsStore.refreshSession(props.sessionId);
    summaryResult.value = "";
    summarizedMsgIds.value = [];
    mode.value = "view";
    selected.value = new Set();
    await loadContext();
  } catch (e) {
    summaryResult.value = `Error: ${(e as Error)?.message ?? e}`;
  }
}
</script>

<style scoped>
.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 14px;
  background: #16213e;
  border-bottom: 1px solid #2a2a4a;
}
.back-btn {
  background: none;
  border: none;
  color: #a0a0b8;
  font-size: 16px;
  padding: 4px 8px;
}
.title {
  color: #e0e0e0;
  font-size: 16px;
  font-weight: 600;
}
.spacer {
  width: 50px;
}
.body {
  flex: 1;
  overflow-y: auto;
  padding: 14px;
}
.loading-text {
  color: #a0a0b8;
  text-align: center;
  margin-top: 40px;
}

/* Mode */
.mode-row {
  display: flex;
  gap: 10px;
  margin-bottom: 14px;
}
.mode-btn {
  flex: 1;
  background: #16213e;
  border-radius: 8px;
  padding: 10px;
  color: #888;
  font-size: 14px;
  border: 1px solid #2a2a4a;
}
.mode-btn.active {
  border-color: #e94560;
  background: rgba(233, 69, 96, 0.1);
  color: #e94560;
  font-weight: 600;
}

/* System */
.section-hint {
  color: #10b981;
  font-size: 11px;
  margin-bottom: 8px;
}
.system-group {
  margin-bottom: 10px;
}
.system-toggle {
  background: none;
  border: none;
  color: #a0a0b8;
  font-size: 13px;
  padding: 0;
  margin-bottom: 6px;
  text-align: left;
}
.system-toggle-text {
  color: inherit;
  font-size: 13px;
}
.system-block {
  display: block;
  width: 100%;
  text-align: left;
  background: #16213e;
  border-radius: 8px;
  padding: 10px;
  margin-bottom: 8px;
  border: 1px solid #2a2a4a;
  cursor: pointer;
}
.system-role {
  color: #e94560;
  font-size: 11px;
  margin-bottom: 4px;
}
.agent-role {
  font-size: 11px;
  margin-bottom: 4px;
  font-weight: 600;
}
.system-content {
  color: #888;
  font-size: 12px;
  line-height: 17px;
}
.clamp-8 {
  display: -webkit-box;
  -webkit-line-clamp: 8;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.clamp-10 {
  display: -webkit-box;
  -webkit-line-clamp: 10;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.entry-list {
  background: rgba(0, 0, 0, 0.2);
  border-radius: 6px;
  padding: 8px;
  margin: 0 0 8px 12px;
}
.entry-item {
  color: #f0c040;
  font-size: 11px;
  line-height: 16px;
}

/* Messages */
.msg-row {
  display: flex;
  align-items: flex-start;
  padding: 8px 10px;
  border-bottom: 1px solid #1a1a2e;
  border-radius: 6px;
  margin-bottom: 2px;
}
.msg-row.selected {
  background: rgba(233, 69, 96, 0.08);
}
.check-area {
  padding: 2px 10px 0 0;
  cursor: pointer;
}
.checkbox {
  width: 20px;
  height: 20px;
  border-radius: 4px;
  border: 1px solid #555;
  display: flex;
  align-items: center;
  justify-content: center;
}
.checkbox.checked {
  background: #e94560;
  border-color: #e94560;
}
.checkmark {
  color: #fff;
  font-size: 12px;
  font-weight: 700;
}
.msg-content {
  flex: 1;
  cursor: pointer;
}
.msg-role {
  color: #3b82f6;
  font-size: 11px;
  font-weight: 600;
  margin-bottom: 2px;
}
.msg-role.user {
  color: #e94560;
}
.msg-preview {
  color: #c0c0c0;
  font-size: 13px;
  line-height: 18px;
}
.clamp-3 {
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.delete-btn {
  background: none;
  border: none;
  color: #e94560;
  font-size: 16px;
  font-weight: 700;
  padding: 2px 0 0 8px;
}

/* Summary */
.summary-section {
  margin-top: 16px;
}
.section-label {
  color: #a0a0b8;
  font-size: 13px;
  margin-bottom: 6px;
  display: block;
}
.prompt-input {
  width: 100%;
  background: #1a1a2e;
  color: #e0e0e0;
  border-radius: 8px;
  padding: 12px;
  font-size: 13px;
  border: 1px solid #2a2a4a;
  min-height: 70px;
  resize: vertical;
  margin-bottom: 12px;
}
.prompt-input::placeholder {
  color: #555;
}
.select-all {
  background: none;
  border: none;
  color: #3b82f6;
  font-size: 13px;
  padding: 0;
  margin-bottom: 10px;
}
.summarize-btn {
  width: 100%;
  background: #e94560;
  border: none;
  border-radius: 10px;
  padding: 14px;
  color: #fff;
  font-size: 15px;
  font-weight: 600;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
}
.summarize-btn:disabled {
  opacity: 0.7;
}
.spinner {
  width: 14px;
  height: 14px;
  border: 2px solid rgba(255, 255, 255, 0.4);
  border-top-color: #fff;
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
}
@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
.result-box {
  margin-top: 14px;
  background: #16213e;
  border-radius: 12px;
  padding: 16px;
  border: 1px solid #2a2a4a;
}
.result-label {
  color: #888;
  font-size: 12px;
  margin-bottom: 8px;
}
.result-text {
  color: #e0e0e0;
  font-size: 14px;
  line-height: 20px;
  white-space: pre-wrap;
}
.result-btns {
  display: flex;
  gap: 10px;
  margin-top: 12px;
}
.apply-btn {
  flex: 1;
  background: #3b82f6;
  border: none;
  border-radius: 8px;
  padding: 12px;
  color: #fff;
  font-size: 14px;
  font-weight: 600;
}
.discard-btn {
  flex: 1;
  border-radius: 8px;
  padding: 12px;
  background: none;
  border: 1px solid #555;
  color: #a0a0b8;
  font-size: 14px;
}

/* Detail overlay */
.detail-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.7);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 60;
}
.detail-box {
  background: #16213e;
  border-radius: 16px;
  width: min(92%, 640px);
  max-height: 80%;
  display: flex;
  flex-direction: column;
  border: 1px solid #2a2a4a;
}
.detail-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px;
  border-bottom: 1px solid #2a2a4a;
}
.detail-title {
  color: #e0e0e0;
  font-size: 16px;
  font-weight: 600;
}
.detail-close {
  background: none;
  border: none;
  color: #e94560;
  font-size: 20px;
  font-weight: 700;
  padding: 0;
}
.detail-body {
  padding: 16px;
  overflow-y: auto;
}
.detail-text {
  color: #e0e0e0;
  font-size: 14px;
  line-height: 22px;
  white-space: pre-wrap;
}
</style>
