// src/components/MessageBubble.tsx
import React, { useState } from "react";
import { View, Text, TouchableOpacity, StyleSheet } from "react-native";
import MarkdownRenderer from "./MarkdownRenderer";
import { replacePlaceholders } from "../utils/placeholders";
import type { ChatMessage } from "../store/sessions";

interface Props {
  message: ChatMessage;
  charName: string;
  userName: string;
}

export default function MessageBubble({ message, charName, userName }: Props) {
  const isUser = message.role === "user";
  const isStatus = message.messageType === "status";
  const [thinkingExpanded, setThinkingExpanded] = useState(false);
  const [workflowExpanded, setWorkflowExpanded] = useState(false);

  if (message.role === "system" && !isStatus) return null;

  // ---- Status 消息特殊渲染 ----
  if (isStatus) {
    return (
      <View style={styles.statusBubble}>
        <TouchableOpacity
          onPress={() => setThinkingExpanded(!thinkingExpanded)}
        >
          <Text style={styles.statusHeader}>
            {thinkingExpanded ? "▼" : "▶"} 📊 Status Update
          </Text>
          {thinkingExpanded && (
            <MarkdownRenderer content={message.content} isUser={false} />
          )}
        </TouchableOpacity>
      </View>
    );
  }

  const displayContent = replacePlaceholders(message.content, charName, userName);

  // 解析思维链
  const thinkPatterns = [
    { open: /<thinking>/i, close: /<\/thinking>/i },
    { open: /【思考】/, close: /【\/思考】/ },
    { open: /\{思考\}/, close: /\{\/思考\}/ },
  ];

  let thinking = "";
  let body = displayContent;

  for (const pat of thinkPatterns) {
    const openMatch = displayContent.match(pat.open);
    if (!openMatch) continue;
    const openEnd = openMatch.index! + openMatch[0].length;
    const closeMatch = displayContent.match(pat.close);
    if (closeMatch) {
      thinking = displayContent.slice(openEnd, closeMatch.index!).trim();
      body = displayContent.slice(closeMatch.index! + closeMatch[0].length).trim();
    } else {
      thinking = displayContent.slice(openEnd).trim();
      body = "";
    }
    break;
  }

  thinking = thinking.replace(/^\n+|\n+$/g, "");
  body = body.replace(/^\n+|\n+$/g, "");

  const wf = message.workflowV2;

  return (
    <View
      style={[
        styles.bubble,
        isUser ? styles.userBubble : styles.assistantBubble,
      ]}
    >
      {/* Agent V2 Workflow（三 Agent 架构） */}
      {!isUser && wf ? (
        <TouchableOpacity
          style={styles.thinkToggle}
          onPress={() => setWorkflowExpanded(!workflowExpanded)}
        >
          <Text style={styles.thinkToggleText}>
            {workflowExpanded ? "▼" : "▶"} ⚙ Agent Workflow
            {" · "}Lore: P{wf.loreCounts.planner}/W{wf.loreCounts.writer}/S{wf.loreCounts.status}
          </Text>

          {workflowExpanded && (
            <View style={styles.thinkContent}>
              {/* Planning Guide (可折叠) */}
              <Text style={styles.workflowSectionTitle}>
                📝 Planning Agent — Writing Guide
              </Text>
              <Text style={styles.workflowDetail} numberOfLines={15}>
                {wf.writingGuide.slice(0, 800)}
                {wf.writingGuide.length > 800 ? "\n... (truncated)" : ""}
              </Text>

              {/* Status Bar 预览 */}
              {wf.statusBar ? (
                <>
                  <Text style={styles.workflowSectionTitle}>
                    📊 Status Manager — Status Bar
                  </Text>
                  <Text style={styles.workflowDetail} numberOfLines={10}>
                    {wf.statusBar.slice(0, 400)}
                    {wf.statusBar.length > 400 ? "\n... (truncated, see full status below)" : ""}
                  </Text>
                </>
              ) : null}
            </View>
          )}
        </TouchableOpacity>
      ) : null}

      {/* 思维链 */}
      {!isUser && thinking ? (
        <TouchableOpacity
          style={styles.thinkToggle}
          onPress={() => setThinkingExpanded(!thinkingExpanded)}
        >
          <Text style={styles.thinkToggleText}>
            {thinkingExpanded ? "▼" : "▶"} Chain of Thought
          </Text>
          {thinkingExpanded && (
            <Text style={styles.thinkContent}>{thinking}</Text>
          )}
        </TouchableOpacity>
      ) : null}

      {/* 正式回复 */}
      {body ? (
        <MarkdownRenderer content={body} isUser={isUser} />
      ) : thinking ? (
        <Text style={styles.waiting}>Generating...</Text>
      ) : (
        <MarkdownRenderer content={displayContent} isUser={isUser} />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  bubble: {
    maxWidth: "85%",
    borderRadius: 14,
    padding: 12,
    marginHorizontal: 14,
    marginVertical: 4,
  },
  userBubble: {
    backgroundColor: "#e94560",
    alignSelf: "flex-end",
  },
  assistantBubble: {
    backgroundColor: "#0f3460",
    alignSelf: "flex-start",
  },
  // Status message
  statusBubble: {
    maxWidth: "92%",
    borderRadius: 10,
    padding: 10,
    marginHorizontal: 14,
    marginVertical: 6,
    backgroundColor: "#1a2332",
    alignSelf: "center",
    borderWidth: 1,
    borderColor: "#2a3a4a",
  },
  statusHeader: {
    color: "#10b981",
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 4,
  },
  // Thinking
  thinkToggle: {
    marginBottom: 8,
  },
  thinkToggleText: {
    color: "#a0a0b8",
    fontSize: 12,
    fontWeight: "600",
  },
  thinkContent: {
    color: "#888",
    fontSize: 11,
    lineHeight: 16,
    fontFamily: "monospace",
    marginTop: 4,
    padding: 8,
    backgroundColor: "rgba(0,0,0,0.3)",
    borderRadius: 6,
  },
  waiting: {
    color: "#666",
    fontSize: 13,
    fontStyle: "italic",
  },
  // Agent workflow styles
  workflowSectionTitle: {
    color: "#10b981",
    fontSize: 11,
    fontWeight: "700",
    marginTop: 8,
    marginBottom: 2,
  },
  workflowDetail: {
    color: "#777",
    fontSize: 10,
    lineHeight: 14,
    marginTop: 2,
  },
});

// fake/strange/frontend/src/components/MessageBubble.vue
<template>
  <!-- Status message (centered, collapsible) -->
  <div v-if="isStatus" class="status-bubble">
    <button class="status-header" @click="thinkingExpanded = !thinkingExpanded">
      {{ thinkingExpanded ? "▼" : "▶" }} 📊 Status Update
    </button>
    <div
      v-if="thinkingExpanded"
      class="md-body md-assistant"
      v-html="renderMarkdown(message.content)"
    ></div>
  </div>

  <!-- Image message -->
  <div v-else-if="isImage" class="image-bubble">
    <img :src="message.imageUrl" alt="生成图片" class="gen-img" />
  </div>

  <!-- Normal message (system & non-status is not rendered) -->
  <div
    v-else-if="message.role !== 'system'"
    class="bubble"
    :class="isUser ? 'user-bubble' : 'assistant-bubble'"
  >
    <!-- Chain of Thought -->
    <div v-if="!isUser && parsed.thinking" class="think-toggle">
      <button class="think-toggle-text" @click="thinkingExpanded = !thinkingExpanded">
        {{ thinkingExpanded ? "▼" : "▶" }} Chain of Thought
      </button>
      <div v-if="thinkingExpanded" class="think-content">{{ parsed.thinking }}</div>
    </div>

    <!-- Body -->
    <div
      v-if="parsed.body"
      class="md-body"
      :class="isUser ? 'md-user' : 'md-assistant'"
      v-html="renderMarkdown(parsed.body)"
    ></div>
    <div v-else-if="parsed.thinking" class="waiting">Generating...</div>
    <div
      v-else
      class="md-body"
      :class="isUser ? 'md-user' : 'md-assistant'"
      v-html="renderMarkdown(parsed.displayContent)"
    ></div>

    <!-- 元数据表（调试用，后续会隐藏） -->
    <div v-if="!isUser && message.replyMeta" class="meta-debug">
      📋 生图={{ message.replyMeta.generateImage ? "是" : "否" }}
      <span v-if="message.replyMeta.imageReason">（{{ message.replyMeta.imageReason }}）</span>
    </div>

    <!-- 生图按钮（右下角） -->
    <div v-if="!isUser && message.content" class="bubble-actions">
      <button class="gen-btn" :disabled="generating" @click.stop="emit('generate-image', message.id)">
        {{ generating ? "生成中…" : "🖼 生图" }}
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import type { ChatMessage } from "../types";
import { renderMarkdown, replacePlaceholders } from "../utils/markdown";

const props = defineProps<{
  message: ChatMessage;
  charName: string;
  userName: string;
  generating?: boolean;
}>();
const emit = defineEmits<{ (e: "generate-image", id: string): void }>();

const isUser = computed(() => props.message.role === "user");
const isStatus = computed(() => props.message.messageType === "status");
const isImage = computed(() => props.message.messageType === "image");

const thinkingExpanded = ref(false);

const THINK_PATTERNS: { open: RegExp; close: RegExp }[] = [
  { open: /<thinking>/i, close: /<\/thinking>/i },
  { open: /【思考】/, close: /【\/思考】/ },
  { open: /\{思考\}/, close: /\{\/思考\}/ },
];

const parsed = computed(() => {
  const displayContent = replacePlaceholders(
    props.message.content,
    props.charName,
    props.userName
  );

  let thinking = "";
  let body = displayContent;

  for (const pat of THINK_PATTERNS) {
    const openMatch = displayContent.match(pat.open);
    if (!openMatch) continue;
    const openEnd = (openMatch.index ?? 0) + openMatch[0].length;
    const closeMatch = displayContent.match(pat.close);
    if (closeMatch) {
      thinking = displayContent.slice(openEnd, closeMatch.index ?? 0).trim();
      body = displayContent.slice((closeMatch.index ?? 0) + closeMatch[0].length).trim();
    } else {
      thinking = displayContent.slice(openEnd).trim();
      body = "";
    }
    break;
  }

  thinking = thinking.replace(/^\n+|\n+$/g, "");
  body = body.replace(/^\n+|\n+$/g, "");

  return { thinking, body, displayContent };
});
</script>

<style scoped>
.bubble {
  max-width: 85%;
  border-radius: 14px;
  padding: 12px;
  margin: 4px 14px;
}
.user-bubble {
  background: #e94560;
  align-self: flex-end;
}
.assistant-bubble {
  background: #0f3460;
  align-self: flex-start;
}

/* Status message */
.status-bubble {
  max-width: 92%;
  border-radius: 10px;
  padding: 10px;
  margin: 6px 14px;
  background: #1a2332;
  align-self: center;
  border: 1px solid #2a3a4a;
}
.status-header {
  background: none;
  border: none;
  color: #10b981;
  font-size: 12px;
  font-weight: 600;
  margin-bottom: 4px;
  padding: 0;
  text-align: left;
  width: 100%;
}

/* Image message */
.image-bubble {
  align-self: flex-start;
  margin: 4px 14px;
  max-width: 85%;
}
.gen-img {
  display: block;
  max-width: 100%;
  max-height: 420px;
  border-radius: 12px;
  border: 1px solid #2a2a4a;
}

/* Thinking toggle */
.think-toggle {
  margin-bottom: 8px;
}
.think-toggle-text {
  background: none;
  border: none;
  color: #a0a0b8;
  font-size: 12px;
  font-weight: 600;
  padding: 0;
  text-align: left;
}
.think-content {
  color: #888;
  font-size: 11px;
  line-height: 16px;
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  margin-top: 4px;
  padding: 8px;
  background: rgba(0, 0, 0, 0.3);
  border-radius: 6px;
  white-space: pre-wrap;
}
.waiting {
  color: #666;
  font-size: 13px;
  font-style: italic;
}

/* 元数据表（调试） */
.meta-debug {
  margin-top: 8px;
  padding-top: 6px;
  border-top: 1px dashed rgba(255, 255, 255, 0.15);
  color: #f0c040;
  font-size: 11px;
  line-height: 16px;
}

/* 生图按钮 */
.bubble-actions {
  display: flex;
  justify-content: flex-end;
  margin-top: 8px;
}
.gen-btn {
  background: rgba(139, 92, 246, 0.18);
  border: 1px solid rgba(139, 92, 246, 0.5);
  border-radius: 8px;
  color: #c4b5fd;
  font-size: 12px;
  font-weight: 600;
  padding: 4px 10px;
  transition: background-color 0.15s ease;
}
.gen-btn:hover {
  background: rgba(139, 92, 246, 0.32);
}
.gen-btn:disabled {
  opacity: 0.5;
  cursor: default;
}
</style>
