// fake/strange/frontend/src/components/LoreBookEditor.vue
<template>
  <div v-if="visible" class="sheet">
    <header class="header">
      <button class="back-btn" @click="emit('close')">← Back</button>
      <span class="title">LoreBook</span>
      <button class="add-btn" @click="openNew">+ Add</button>
    </header>

    <!-- Entry list -->
    <div v-if="editIdx === null" class="list">
      <div v-if="entries.length === 0" class="empty">
        No entries yet. Tap "+ Add" to create one.
      </div>
      <div v-else>
        <div v-for="(entry, idx) in entries" :key="idx" class="entry-card">
          <div class="entry-content" @click="openEdit(idx)">
            <div class="entry-title">{{ entry.comment || "(no title)" }}</div>
            <div v-if="entryKeys(entry)" class="entry-keys">Keys: {{ entryKeys(entry) }}</div>
            <div class="entry-preview">{{ entry.content || "(empty)" }}</div>
            <div class="entry-meta">
              <span class="meta-text">
                {{ entry.position === "after_char" ? "after" : "before" }}
                · {{ entry.constant ? "constant" : "keyword" }}
              </span>
            </div>
          </div>
          <div class="entry-actions">
            <ToggleSwitch
              :model-value="entry.enabled !== false"
              color="#e94560"
              @update:model-value="toggleEntry(idx)"
            />
            <button class="delete-icon" @click="deleteEntry(idx)">✕</button>
          </div>
        </div>
      </div>
    </div>

    <!-- Entry form -->
    <div v-else class="form">
      <div class="form-title">{{ editIdx === -1 ? "New Entry" : "Edit Entry" }}</div>

      <label class="label">Title</label>
      <input v-model="form.title" class="input" placeholder="Entry display name" />

      <label class="label">Keys (comma-separated)</label>
      <input v-model="form.keys" class="input" placeholder="keyword1, keyword2" />

      <label class="label">Content</label>
      <textarea v-model="form.content" class="input content-input" placeholder="Entry content..."></textarea>

      <div class="switch-row">
        <span class="label">Constant</span>
        <ToggleSwitch v-model="form.constant" color="#e94560" />
      </div>

      <div class="switch-row">
        <span class="label">Enabled</span>
        <ToggleSwitch v-model="form.enabled" color="#e94560" />
      </div>

      <label class="label">Position</label>
      <div class="seg-row">
        <button
          class="seg-btn"
          :class="{ active: form.position === 'before_char' }"
          @click="form.position = 'before_char'"
        >
          Before Char
        </button>
        <button
          class="seg-btn"
          :class="{ active: form.position === 'after_char' }"
          @click="form.position = 'after_char'"
        >
          After Char
        </button>
      </div>

      <div class="form-btns">
        <button class="cancel-btn" @click="editIdx = null">Cancel</button>
        <button class="save-btn" @click="saveEntry">Save Entry</button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import { useSessionsStore } from "../stores/sessions";
import type { LoreBookEntry } from "../types";
import ToggleSwitch from "./ToggleSwitch.vue";

const props = defineProps<{ visible: boolean; sessionId: string }>();
const emit = defineEmits<{ (e: "close"): void }>();

const sessionsStore = useSessionsStore();

interface EntryForm {
  title: string;
  keys: string;
  content: string;
  constant: boolean;
  enabled: boolean;
  position: "before_char" | "after_char";
}

const defaultEntry = (): EntryForm => ({
  title: "",
  keys: "",
  content: "",
  constant: false,
  enabled: true,
  position: "before_char",
});

const editIdx = ref<number | null>(null);
const form = ref<EntryForm>(defaultEntry());

const entries = computed<LoreBookEntry[]>(() => {
  const s = sessionsStore.getById(props.sessionId);
  return (s?.characterCard.data.character_book?.entries ?? []) as LoreBookEntry[];
});

function entryToForm(e: LoreBookEntry): EntryForm {
  return {
    title: e.comment ?? "",
    keys: (e.keys ?? []).join(", "),
    content: e.content ?? "",
    constant: e.constant ?? false,
    enabled: e.enabled ?? true,
    position: e.position === "after_char" ? "after_char" : "before_char",
  };
}

function formToEntry(f: EntryForm): LoreBookEntry {
  return {
    keys: f.keys.split(",").map((k) => k.trim()).filter(Boolean),
    content: f.content,
    comment: f.title,
    constant: f.constant,
    enabled: f.enabled,
    position: f.position,
    insertion_order: 100,
    case_sensitive: false,
    selective: false,
    secondary_keys: [],
  };
}

function entryKeys(e: LoreBookEntry): string {
  return e.keys && e.keys.length > 0 ? e.keys.join(", ") : "";
}

async function persist(updated: LoreBookEntry[]): Promise<void> {
  const s = sessionsStore.getById(props.sessionId);
  if (!s) return;
  const book = s.characterCard.data.character_book;
  await sessionsStore.patchCharacterBook(props.sessionId, {
    ...(book ?? {}),
    entries: updated,
    name: book?.name ?? "",
    scan_depth: book?.scan_depth ?? 50,
    case_sensitive: book?.case_sensitive ?? false,
    recursive_scanning: book?.recursive_scanning ?? false,
  });
}

function openNew(): void {
  form.value = defaultEntry();
  editIdx.value = -1;
}

function openEdit(idx: number): void {
  form.value = entryToForm(entries.value[idx]);
  editIdx.value = idx;
}

async function saveEntry(): Promise<void> {
  const entryData = formToEntry(form.value);
  let updated: LoreBookEntry[];
  if (editIdx.value === -1) {
    updated = [...entries.value, entryData];
  } else if (editIdx.value !== null) {
    updated = [...entries.value];
    updated[editIdx.value] = { ...entries.value[editIdx.value], ...entryData };
  } else {
    return;
  }
  await persist(updated);
  editIdx.value = null;
}

async function deleteEntry(idx: number): Promise<void> {
  await persist(entries.value.filter((_, i) => i !== idx));
}

async function toggleEntry(idx: number): Promise<void> {
  const updated = [...entries.value];
  updated[idx] = { ...updated[idx], enabled: !updated[idx].enabled };
  await persist(updated);
}
</script>

<style scoped>
.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 14px;
  background: #16213e;
  border-bottom: 1px solid #2a2a4a;
}
.back-btn {
  background: none;
  border: none;
  color: #a0a0b8;
  font-size: 16px;
  padding: 4px 8px;
}
.title {
  color: #e0e0e0;
  font-size: 18px;
  font-weight: 600;
}
.add-btn {
  background: none;
  border: none;
  color: #e94560;
  font-size: 15px;
  font-weight: 600;
  padding: 4px 8px;
}
.list {
  flex: 1;
  overflow-y: auto;
  padding: 14px;
}
.empty {
  color: #555;
  text-align: center;
  margin-top: 80px;
  font-size: 14px;
}
.entry-card {
  background: #16213e;
  border-radius: 12px;
  border: 1px solid #2a2a4a;
  margin-bottom: 10px;
  display: flex;
  align-items: center;
}
.entry-content {
  flex: 1;
  padding: 14px;
  cursor: pointer;
}
.entry-title {
  color: #e0e0e0;
  font-size: 15px;
  font-weight: 600;
  margin-bottom: 2px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.entry-keys {
  color: #e94560;
  font-size: 11px;
  margin-bottom: 4px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.entry-preview {
  color: #a0a0b8;
  font-size: 13px;
  line-height: 18px;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.entry-meta {
  margin-top: 6px;
}
.meta-text {
  color: #555;
  font-size: 11px;
}
.entry-actions {
  padding: 0 10px;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
}
.delete-icon {
  background: none;
  border: none;
  color: #e94560;
  font-size: 16px;
  font-weight: 700;
  padding: 0;
}
.form {
  flex: 1;
  overflow-y: auto;
  padding: 16px;
}
.form-title {
  color: #e0e0e0;
  font-size: 20px;
  font-weight: 700;
  margin-bottom: 20px;
}
.label {
  color: #a0a0b8;
  font-size: 14px;
  margin: 12px 0 6px;
  display: block;
}
.input {
  width: 100%;
  background: #16213e;
  color: #e0e0e0;
  border-radius: 10px;
  padding: 14px;
  font-size: 15px;
  border: 1px solid #2a2a4a;
}
.input::placeholder {
  color: #666;
}
.content-input {
  min-height: 120px;
  resize: vertical;
}
.switch-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 8px;
}
.switch-row .label {
  margin: 0;
}
.seg-row {
  display: flex;
  gap: 10px;
}
.seg-btn {
  flex: 1;
  background: #16213e;
  border-radius: 8px;
  padding: 12px;
  color: #888;
  font-size: 14px;
  border: 1px solid #2a2a4a;
}
.seg-btn.active {
  border-color: #e94560;
  background: rgba(233, 69, 96, 0.1);
  color: #e94560;
  font-weight: 600;
}
.form-btns {
  display: flex;
  gap: 12px;
  margin-top: 24px;
  margin-bottom: 40px;
}
.cancel-btn {
  flex: 1;
  border-radius: 10px;
  padding: 14px;
  background: none;
  border: 1px solid #2a2a4a;
  color: #a0a0b8;
  font-size: 15px;
}
.save-btn {
  flex: 1;
  background: #e94560;
  border: none;
  border-radius: 10px;
  padding: 14px;
  color: #fff;
  font-size: 15px;
  font-weight: 600;
}
</style>

// src/components/LoreBookEditor.tsx
import React, { useState, useEffect } from "react";
import {
  Modal,
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  ScrollView,
  Switch,
} from "react-native";
import { getSession, updateCharacterBook } from "../store/sessions";

interface Props {
  visible: boolean;
  sessionId: string;
  onClose: () => void;
}

interface EntryForm {
  title: string;
  keys: string;
  content: string;
  constant: boolean;
  enabled: boolean;
  position: "before_char" | "after_char";
}

type EntryData = any;

const defaultEntry = (): EntryForm => ({
  title: "",
  keys: "",
  content: "",
  constant: false,
  enabled: true,
  position: "before_char",
});

function entryToForm(e: EntryData): EntryForm {
  return {
    title: e.comment ?? "",
    keys: (e.keys ?? []).join(", "),
    content: e.content ?? "",
    constant: e.constant ?? false,
    enabled: e.enabled ?? true,
    position: e.position === "after_char" ? "after_char" : "before_char",
  };
}

function formToEntry(f: EntryForm): EntryData {
  return {
    keys: f.keys.split(",").map((k) => k.trim()).filter(Boolean),
    content: f.content,
    comment: f.title,
    constant: f.constant,
    enabled: f.enabled,
    position: f.position,
    insertion_order: 100,
    case_sensitive: false,
    selective: false,
    secondary_keys: [],
  };
}

export default function LoreBookEditor({ visible, sessionId, onClose }: Props) {
  const session = getSession(sessionId);
  const [entries, setEntries] = useState<EntryData[]>([]);
  const [editIdx, setEditIdx] = useState<number | null>(null);
  const [form, setForm] = useState<EntryForm>(defaultEntry());

  // 加载/刷新 entries
  useEffect(() => {
    if (!visible) return;
    const s = getSession(sessionId);
    const book = s?.characterCard.data.character_book;
    setEntries(book?.entries ?? []);
  }, [visible, sessionId]);

  const persist = (updated: EntryData[]) => {
    const s = getSession(sessionId);
    if (!s) return;
    const book = s.characterCard.data.character_book;
    updateCharacterBook(sessionId, {
      ...(book ?? {}),
      entries: updated,
      name: book?.name ?? "",
      scan_depth: book?.scan_depth ?? 50,
      case_sensitive: book?.case_sensitive ?? false,
      recursive_scanning: book?.recursive_scanning ?? false,
    });
    setEntries(updated);
  };

  const openNew = () => {
    setForm(defaultEntry());
    setEditIdx(-1);
  };

  const openEdit = (idx: number) => {
    setForm(entryToForm(entries[idx]));
    setEditIdx(idx);
  };

  const saveEntry = () => {
    const entryData = formToEntry(form);
    let updated: EntryData[];
    if (editIdx === -1) {
      updated = [...entries, entryData];
    } else if (editIdx !== null) {
      updated = [...entries];
      updated[editIdx] = { ...entries[editIdx], ...entryData };
    } else return;
    persist(updated);
    setEditIdx(null);
  };

  const deleteEntry = (idx: number) => {
    persist(entries.filter((_: any, i: number) => i !== idx));
  };

  const toggleEntry = (idx: number) => {
    const updated = [...entries];
    updated[idx] = { ...updated[idx], enabled: !updated[idx].enabled };
    persist(updated);
  };

  return (
    <Modal visible={visible} animationType="slide" presentationStyle="pageSheet">
      <View style={styles.container}>
        <View style={styles.header}>
          <TouchableOpacity onPress={onClose}>
            <Text style={styles.backBtn}>← Back</Text>
          </TouchableOpacity>
          <Text style={styles.title}>LoreBook</Text>
          <TouchableOpacity onPress={openNew}>
            <Text style={styles.addBtn}>+ Add</Text>
          </TouchableOpacity>
        </View>

        {editIdx === null ? (
          <ScrollView style={styles.list}>
            {entries.length === 0 ? (
              <Text style={styles.empty}>No entries yet. Tap "+ Add" to create one.</Text>
            ) : (
              entries.map((entry: EntryData, idx: number) => {
                const title = entry.comment || "(no title)";
                const keys = entry.keys?.length > 0 ? entry.keys.join(", ") : "";
                return (
                  <View key={idx} style={styles.entryCard}>
                    <TouchableOpacity
                      style={styles.entryContent}
                      onPress={() => openEdit(idx)}
                    >
                      <Text style={styles.entryTitle} numberOfLines={1}>
                        {title}
                      </Text>
                      {keys ? (
                        <Text style={styles.entryKeys} numberOfLines={1}>
                          Keys: {keys}
                        </Text>
                      ) : null}
                      <Text style={styles.entryPreview} numberOfLines={2}>
                        {entry.content || "(empty)"}
                      </Text>
                      <View style={styles.entryMeta}>
                        <Text style={styles.metaText}>
                          {entry.position === "after_char" ? "after" : "before"}
                          {" · "}
                          {entry.constant ? "constant" : "keyword"}
                        </Text>
                      </View>
                    </TouchableOpacity>
                    <View style={styles.entryActions}>
                      <Switch
                        value={entry.enabled !== false}
                        onValueChange={() => toggleEntry(idx)}
                        trackColor={{ false: "#444", true: "#e94560" }}
                      />
                      <TouchableOpacity onPress={() => deleteEntry(idx)}>
                        <Text style={styles.deleteIcon}>✕</Text>
                      </TouchableOpacity>
                    </View>
                  </View>
                );
              })
            )}
          </ScrollView>
        ) : (
          <ScrollView style={styles.form}>
            <Text style={styles.formTitle}>
              {editIdx === -1 ? "New Entry" : "Edit Entry"}
            </Text>

            <Text style={styles.label}>Title</Text>
            <TextInput
              style={styles.input}
              value={form.title}
              onChangeText={(t) => setForm({ ...form, title: t })}
              placeholder="Entry display name"
              placeholderTextColor="#666"
            />

            <Text style={styles.label}>Keys (comma-separated)</Text>
            <TextInput
              style={styles.input}
              value={form.keys}
              onChangeText={(t) => setForm({ ...form, keys: t })}
              placeholder="keyword1, keyword2"
              placeholderTextColor="#666"
            />

            <Text style={styles.label}>Content</Text>
            <TextInput
              style={[styles.input, styles.contentInput]}
              value={form.content}
              onChangeText={(t) => setForm({ ...form, content: t })}
              placeholder="Entry content..."
              placeholderTextColor="#666"
              multiline
              numberOfLines={6}
            />

            <View style={styles.switchRow}>
              <Text style={styles.label}>Constant</Text>
              <Switch
                value={form.constant}
                onValueChange={(v) => setForm({ ...form, constant: v })}
                trackColor={{ false: "#444", true: "#e94560" }}
              />
            </View>

            <View style={styles.switchRow}>
              <Text style={styles.label}>Enabled</Text>
              <Switch
                value={form.enabled}
                onValueChange={(v) => setForm({ ...form, enabled: v })}
                trackColor={{ false: "#444", true: "#e94560" }}
              />
            </View>

            <Text style={styles.label}>Position</Text>
            <View style={styles.segRow}>
              <TouchableOpacity
                style={[styles.segBtn, form.position === "before_char" && styles.segActive]}
                onPress={() => setForm({ ...form, position: "before_char" })}
              >
                <Text style={[styles.segText, form.position === "before_char" && styles.segTextActive]}>
                  Before Char
                </Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={[styles.segBtn, form.position === "after_char" && styles.segActive]}
                onPress={() => setForm({ ...form, position: "after_char" })}
              >
                <Text style={[styles.segText, form.position === "after_char" && styles.segTextActive]}>
                  After Char
                </Text>
              </TouchableOpacity>
            </View>

            <View style={styles.formBtns}>
              <TouchableOpacity style={styles.cancelBtn} onPress={() => setEditIdx(null)}>
                <Text style={styles.cancelText}>Cancel</Text>
              </TouchableOpacity>
              <TouchableOpacity style={styles.saveBtn} onPress={saveEntry}>
                <Text style={styles.saveText}>Save Entry</Text>
              </TouchableOpacity>
            </View>
          </ScrollView>
        )}
      </View>
    </Modal>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#1a1a2e" },
  header: {
    flexDirection: "row", justifyContent: "space-between", alignItems: "center",
    paddingHorizontal: 14, paddingTop: 54, paddingBottom: 12,
    backgroundColor: "#16213e", borderBottomWidth: 1, borderBottomColor: "#2a2a4a",
  },
  backBtn: { color: "#a0a0b8", fontSize: 16 },
  title: { color: "#e0e0e0", fontSize: 18, fontWeight: "600" },
  addBtn: { color: "#e94560", fontSize: 15, fontWeight: "600" },
  list: { flex: 1, padding: 14 },
  empty: { color: "#555", textAlign: "center", marginTop: 80, fontSize: 14 },

  entryCard: {
    backgroundColor: "#16213e", borderRadius: 12,
    borderWidth: 1, borderColor: "#2a2a4a", marginBottom: 10,
    flexDirection: "row", alignItems: "center",
  },
  entryContent: { flex: 1, padding: 14 },
  entryTitle: { color: "#e0e0e0", fontSize: 15, fontWeight: "600", marginBottom: 2 },
  entryKeys: { color: "#e94560", fontSize: 11, marginBottom: 4 },
  entryPreview: { color: "#a0a0b8", fontSize: 13, lineHeight: 18 },
  entryMeta: { flexDirection: "row", marginTop: 6 },
  metaText: { color: "#555", fontSize: 11 },
  entryActions: { paddingRight: 10, alignItems: "center", gap: 8 },
  deleteIcon: { color: "#e94560", fontSize: 16, fontWeight: "700" },

  form: { flex: 1, padding: 16 },
  formTitle: { color: "#e0e0e0", fontSize: 20, fontWeight: "700", marginBottom: 20 },
  label: { color: "#a0a0b8", fontSize: 14, marginBottom: 6, marginTop: 12 },
  input: {
    backgroundColor: "#16213e", color: "#e0e0e0", borderRadius: 10,
    padding: 14, fontSize: 15, borderWidth: 1, borderColor: "#2a2a4a",
  },
  contentInput: { minHeight: 120, textAlignVertical: "top" },
  switchRow: {
    flexDirection: "row", justifyContent: "space-between",
    alignItems: "center", marginTop: 8,
  },
  segRow: { flexDirection: "row", gap: 10 },
  segBtn: {
    flex: 1, backgroundColor: "#16213e", borderRadius: 8,
    padding: 12, alignItems: "center", borderWidth: 1, borderColor: "#2a2a4a",
  },
  segActive: { borderColor: "#e94560", backgroundColor: "rgba(233,69,96,0.1)" },
  segText: { color: "#888", fontSize: 14 },
  segTextActive: { color: "#e94560", fontWeight: "600" },
  formBtns: { flexDirection: "row", gap: 12, marginTop: 24, marginBottom: 40 },
  cancelBtn: {
    flex: 1, borderRadius: 10, padding: 14,
    alignItems: "center", borderWidth: 1, borderColor: "#2a2a4a",
  },
  cancelText: { color: "#a0a0b8", fontSize: 15 },
  saveBtn: {
    flex: 1, backgroundColor: "#e94560", borderRadius: 10,
    padding: 14, alignItems: "center",
  },
  saveText: { color: "#fff", fontSize: 15, fontWeight: "600" },
});
